# Generated by Django 2.0.13 on 2021-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='preco',
            field=models.FloatField(),
        ),
    ]
