# Generated by Django 2.0.13 on 2021-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210816_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
