# Generated by Django 3.2.6 on 2021-08-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20210818_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarto',
            old_name='id',
            new_name='quarto_id',
        ),
    ]
