# Generated by Django 3.2.6 on 2021-08-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rename_id_quarto_quarto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='camas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='frigobar',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarto',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='preco',
            field=models.FloatField(),
        ),
    ]
