# Generated by Django 3.2.6 on 2021-08-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210823_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='frigobar',
            field=models.BooleanField(default=False),
        ),
    ]
