# Generated by Django 3.2.6 on 2021-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id',
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
